name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - pip:
    # TODO: add pin
    # - jupyterlite-core==0.1.0b19
    - jupyterlite-core
    - jupyterlite-xeus-python==0.6.2
